"""create_worker_codes_table

Revision ID: 1706b8a149fb
Revises: b03176ebe41f
Create Date: 2026-04-24 10:29:23.169909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1706b8a149fb'
down_revision: Union[str, Sequence[str], None] = 'b03176ebe41f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker_codes',
    sa.Column('code_id', sa.Uuid(), nullable=False),
    sa.Column('code_name', sa.String(length=100), nullable=False),
    sa.Column('code_description', sa.String(length=255), nullable=False),
    sa.Column('pay_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('code_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('worker_codes')
    # ### end Alembic commands ###
