"""strip_block_rows_add_row_portions

Revision ID: 61db773101fb
Revises: 70357dceb796
Create Date: 2026-04-27 12:29:34.375699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61db773101fb'
down_revision: Union[str, Sequence[str], None] = '70357dceb796'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('row_portions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('row_id', sa.Uuid(), nullable=False),
    sa.Column('portion_label', sa.String(), nullable=True),
    sa.Column('sequence_no', sa.Integer(), nullable=True),
    sa.Column('variety_id', sa.Uuid(), nullable=False),
    sa.Column('clone_id', sa.Uuid(), nullable=True),
    sa.Column('rootstock_id', sa.Uuid(), nullable=True),
    sa.Column('planting_year', sa.Integer(), nullable=True),
    sa.Column('tree_count', sa.Integer(), nullable=True),
    sa.Column('length_m', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('area_m2', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clone_id'], ['variety_clones.id'], ),
    sa.ForeignKeyConstraint(['rootstock_id'], ['rootstocks.id'], ),
    sa.ForeignKeyConstraint(['row_id'], ['block_rows.id'], ),
    sa.ForeignKeyConstraint(['variety_id'], ['varieties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('block_rows_variety_id_fkey'), 'block_rows', type_='foreignkey')
    op.drop_constraint(op.f('block_rows_clone_id_fkey'), 'block_rows', type_='foreignkey')
    op.drop_constraint(op.f('block_rows_rootstock_id_fkey'), 'block_rows', type_='foreignkey')
    op.drop_column('block_rows', 'planting_year')
    op.drop_column('block_rows', 'variety_id')
    op.drop_column('block_rows', 'area_m2')
    op.drop_column('block_rows', 'tree_spacing_m')
    op.drop_column('block_rows', 'rootstock_id')
    op.drop_column('block_rows', 'tree_count')
    op.drop_column('block_rows', 'clone_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('block_rows', sa.Column('clone_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('block_rows', sa.Column('tree_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('block_rows', sa.Column('rootstock_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('block_rows', sa.Column('tree_spacing_m', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True))
    op.add_column('block_rows', sa.Column('area_m2', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('block_rows', sa.Column('variety_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('block_rows', sa.Column('planting_year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('block_rows_rootstock_id_fkey'), 'block_rows', 'rootstocks', ['rootstock_id'], ['id'])
    op.create_foreign_key(op.f('block_rows_clone_id_fkey'), 'block_rows', 'variety_clones', ['clone_id'], ['id'])
    op.create_foreign_key(op.f('block_rows_variety_id_fkey'), 'block_rows', 'varieties', ['variety_id'], ['id'])
    op.drop_table('row_portions')
    # ### end Alembic commands ###
