"""block_rows_clone_id_nullable

Revision ID: 70357dceb796
Revises: 313f7c949a26
Create Date: 2026-04-27 11:53:02.461837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70357dceb796'
down_revision: Union[str, Sequence[str], None] = '313f7c949a26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('block_rows', 'clone_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('block_rows', 'clone_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
