"""update_workers_uuid7_start_end_dates

Revision ID: b03176ebe41f
Revises: 04dbdf2b3ecf
Create Date: 2026-04-24 10:16:44.592804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b03176ebe41f'
down_revision: Union[str, Sequence[str], None] = '04dbdf2b3ecf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workers', sa.Column('start_date', sa.Date(), nullable=False))
    op.add_column('workers', sa.Column('end_date', sa.Date(), nullable=True))
    op.drop_constraint('workers_pkey', 'workers', type_='primary')
    op.drop_column('workers', 'id')
    op.add_column('workers', sa.Column('id', sa.Uuid(), nullable=False))
    op.create_primary_key('workers_pkey', 'workers', ['id'])
    op.drop_constraint('workers_worker_code_key', 'workers', type_='unique')
    op.drop_column('workers', 'active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workers', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_unique_constraint('workers_worker_code_key', 'workers', ['worker_code'])
    op.drop_constraint('workers_pkey', 'workers', type_='primary')
    op.drop_column('workers', 'id')
    op.add_column('workers', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_primary_key('workers_pkey', 'workers', ['id'])
    op.drop_column('workers', 'end_date')
    op.drop_column('workers', 'start_date')
    # ### end Alembic commands ###
